// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD69jTm-nZpPDJNqdAKhKFV_dggkDXCFI4',
    appId: '1:153690740288:web:bec9346ddfe73cad90f1a5',
    messagingSenderId: '153690740288',
    projectId: 'clean-tracker-c3760',
    authDomain: 'clean-tracker-c3760.firebaseapp.com',
    storageBucket: 'clean-tracker-c3760.firebasestorage.app',
    measurementId: 'G-B0F171C9Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeZJzoT1ScusfptiwWdUBAeACevZGVsCg',
    appId: '1:153690740288:android:523a715042bd749390f1a5',
    messagingSenderId: '153690740288',
    projectId: 'clean-tracker-c3760',
    storageBucket: 'clean-tracker-c3760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg55UegjdeTWWW3Bm5yn1KHh62d9O3o6Y',
    appId: '1:153690740288:ios:c9afe557d46e923f90f1a5',
    messagingSenderId: '153690740288',
    projectId: 'clean-tracker-c3760',
    storageBucket: 'clean-tracker-c3760.firebasestorage.app',
    iosBundleId: 'com.example.cleanTrack',
  );
}
